<div class="bg-content" >
	<div class="row">
		<div class="col-xs-12">
			<h2>
				<i class="glyphicon glyphicon-user"></i><?php echo ($this->id) ? 'Editar Usuário' : 'Novo Usuário' ?> - 
				<button type="reset" class="btn btn-default" onclick="javascript:history.go('-1')">
					<i class="fa fa-hand-o-left"></i> Voltar
				</button>
			</h2>
		</div>
		<br />

		<?php 
		$form = $this->form;
		$form->setAttribute('action',$this->url('user-all/default',array('controller'=>'usuarios','action'=>'cadastro','id' => $this->id)));
		$form->prepare(); ?>
		<?php echo $this->form()->openTag($form); ?>
		<?php $usuario = $form->get('usuario')  ?>
		<div class="row">
			<div class="form-group col-sm-12 <?php echo ($this->formElementErrors($usuario->get('email'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($usuario->get('email')); ?>
				<div class="col-sm-6">
					<?php echo $this->formInput($usuario->get('email')); ?>
				</div>
				<div class="col-sm-6 col-sm-offset-2">
					<div class="help-block"><?php echo $this->formElementErrors($usuario->get('email')); ?></div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="form-group col-sm-12 <?php echo ($this->formElementErrors($usuario->get('usuario'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($usuario->get('usuario')); ?>
				<div class="col-sm-6">
					<?php echo $this->formInput($usuario->get('usuario')); ?>
				</div>
				<div class="col-sm-6 col-sm-offset-2">
					<div class="help-block"><?php echo $this->formElementErrors($usuario->get('usuario')); ?></div>
				</div>
			</div>
		</div>
		<?php if($this->id): ?>
		<div class="row">
			<div class="col-xs-7 alert alert-info col-sm-6 col-sm-offset-2 padding-vertical-none">
				<strong><i class="fa fa-warning fa-fw"></i> Caso não quer que a senha seja alterada, deixe o campo vazio!</strong>
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			</div>
		</div>
		<?php endif;?>


		<div class="row">
			<div class="form-group col-sm-12 <?php echo ($this->formElementErrors($usuario->get('senha'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($usuario->get('senha')); ?>
				<div class="col-sm-6">
					<?php echo $this->formInput($usuario->get('senha')); ?>
				</div>
				<div class="col-sm-6 col-sm-offset-2">
					<div class="help-block"><?php echo $this->formElementErrors($usuario->get('senha')); ?></div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="form-group col-sm-12 <?php echo ($this->formElementErrors($usuario->get('confirmar'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($usuario->get('confirmar')); ?>
				<div class="col-sm-6">
					<?php echo $this->formInput($usuario->get('confirmar')); ?>
				</div>
				<div class="col-sm-10 col-sm-offset-2">
					<div class="help-block"><?php echo $this->formElementErrors($usuario->get('confirmar')); ?></div>
				</div>
			</div>
		</div>

		<div classs="row">
			<div id="div_papel" class="form-group col-sm-12 <?php echo ($this->formElementErrors($usuario->get('papel'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($usuario->get('papel')); ?>
				<div class="col-sm-6">
				<?php echo $this->formSelect($usuario->get('papel')); ?>
				</div>
				<div class="col-sm-6 col-sm-offset-2">
				<div class="help-block"><?php echo $this->formElementErrors($usuario->get('papel')); ?></div>
				</div>
			</div>
		</div>

		<div classs="row">
			<div id="div_empresa" class="form-group col-sm-12 <?php echo ($this->formElementErrors($usuario->get('empresa'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($usuario->get('empresa')); ?>
				<div class="col-sm-6">
				<?php echo $this->formSelect($usuario->get('empresa')); ?>
				</div>
				<div class="col-sm-6 col-sm-offset-2">
				<div class="help-block"><?php echo $this->formElementErrors($usuario->get('empresa')); ?></div>
				</div>
			</div>
		</div>



		<?php $perfil = $usuario->get('perfil'); ?>
		<h2><?php echo $this->formLabel($usuario->get('perfil')); ?></h2>
		<div class="row">
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('pessoa'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('pessoa')); ?>
				<div class="col-sm-9">
					<?php echo $this->formRadio($perfil->get('pessoa')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('pessoa')); ?></div>
				</div>
			</div>

			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('cpf_cnpj'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('cpf_cnpj')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('cpf_cnpj')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('cpf_cnpj')); ?></div>
				</div>
			</div>
		</div>


		<div class="row">
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('nome'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('nome')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('nome')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('nome')); ?></div>
				</div>
			</div>

			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('data_nasc'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('data_nasc')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('data_nasc')); ?>
				</div>	
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('data_nasc')); ?></div>
				</div>
			</div>
		</div>

			
		

		<div class="row">
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('cep'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('cep')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('cep')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('cep')); ?></div>
				</div>
			</div>

			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('endereco'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('endereco')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('endereco')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('endereco')); ?></div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('numero'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('numero')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('numero')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('numero')); ?></div>
				</div>
			</div>
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('complemento'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('complemento')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('complemento')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('complemento')); ?></div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('bairro'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('bairro')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('bairro')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('bairro')); ?></div>
				</div>
			</div>
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('telefone'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('telefone')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('telefone')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('telefone')); ?></div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('celular'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('celular')); ?>
				<div class="col-sm-9">
					<?php echo $this->formInput($perfil->get('celular')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('celular')); ?></div>
				</div>
			</div>
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('estado'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('estado')); ?>
				<div class="col-sm-9">
					<?php echo $this->formSelect($perfil->get('estado')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('estado')); ?></div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="form-group col-sm-offset-6 col-sm-6 <?php echo ($this->formElementErrors($perfil->get('cidade'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('cidade')); ?>
				<div class="col-sm-9" id="div_cidade">
					<?php echo $this->formSelect($perfil->get('cidade')); ?>
					<?php echo $this->formElement($perfil->get('cidade_hidden')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('cidade')); ?></div>
				</div>
			</div>
			<div class="form-group col-sm-offset-6 col-sm-6 <?php echo ($this->formElementErrors($perfil->get('obs'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('obs')); ?>
				<div class="col-sm-9" id="div_cidade">
					<?php echo $this->formElement($perfil->get('obs')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">
					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('obs')); ?></div>
				</div>
			</div>				
		</div>
		
		<div class="row">
			<div class="form-group col-sm-6 <?php echo ($this->formElementErrors($perfil->get('foto'))) ? 'has-error' : '' ; ?>">
				<?php echo $this->formLabel($perfil->get('foto')); ?>
				<?php $value = $perfil->get('foto')->getValue() ?>
				<?php if (!empty($value)) {
					echo $this->formElement($perfil->get('foto_hidden'));
				} 
				?>
				<div class="col-sm-9">
					<?php echo $this->formFile($perfil->get('foto')); ?>
				</div>
				<div class="col-sm-9 col-sm-offset-3">

					<div class="help-block"><?php echo $this->formElementErrors($perfil->get('foto')); ?></div>
				</div>
				<script type="text/javascript">
					$(document).ready(function() {
					    $('#id-input-file').k13_file_input({
					        style:'well',
					        btn_choose:'Arraste a imagem aqui ou click para selecionar',
					        btn_change:null,
					        no_icon:'fa-picture-o',
					        droppable:true,
					        thumbnail:'large',// fit| small
					    });
					});
					</script>
			</div>			
		</div>

		<div class="row">
			<div class="form-group col-sm-offset-6 col-sm-push-9 col-sm-3">
				<?php echo $this->formButton()->openTag($form->get('submit')); ?>
					<i class="fa fa-check"></i> <?php echo  $form->get('submit')->getValue(); ?>
				<?php echo $this->formButton()->closeTag(); ?>
			</div>
		</div>

		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
