<?php
	$form = $this->form;
	$form->setAttribute('action',$this->url('user-auth'));
	$form->prepare(); 
	echo $this->form()->openTag($form); 
	if(count($flashMessages)) {
		foreach ($flashMessages as $msg) { ?>
		<div class="alert alert-warning fade in">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
			<?php echo $msg; ?>
		</div>
		<?php }
	}?>
<div class="login-fields">
	<div class="field">
		<?php echo $this->formElement($form->get('username')); ?>
	</div>
	<div class="field">
		<?php echo $this->formElement($form->get('password')); ?>
	</div>
</div>
<div class="login-actions">
	<span class="login-checkbox">
		<input id="rememberme" class="field login-checkbox" type="checkbox" tabindex="4" name="rememberme"></input>
		<label class="choice" for="rememberme"> Mantenha-me conectado</label>
	</span>
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div> <!-- .actions -->
<?php echo $this->form()->closeTag(); ?>

<div class="login-social">
	Esqueceu a <a href="#">Senha</a>
</div>
